# Generated by Django 3.1.7 on 2021-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_store_app', '0002_auto_20210513_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_type',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='company_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
